[tools]
# general
chezmoi = "latest"
bun = "latest"  # for `npm:` install
node = "latest"  # for `npm:` install
uv = "latest"  # for `pipx:` install
aqua = "latest"
# programming
gh = "latest"
"aqua:dlvhdr/gh-dash" = "latest"
"aqua:boyter/scc" = "latest"
ghq = "latest"
"aqua:microsoft/vscode/code" = "1.107.1"
# shell
"aqua:nushell/nushell" = "latest"
starship = "latest"
zellij = "latest"
# tools
rg = "latest"
fzf = "latest"
fd = "latest"
yazi = "latest"
bottom = "latest"
duf = "latest"
dust = "latest"
lazydocker = "latest"
lazygit = "latest"
# ai
# agents
gemini = "latest"
"aqua:github/copilot-cli" = "latest"
"npm:@sourcegraph/amp" = "latest"
"aqua:anomalyco/opencode" = "latest"
"npm:@openchamber/web" = "latest"
# mcps
"npm:@upstash/context7-mcp" = "latest"

[env]
EDITOR = "hx"

[settings]
npm.package_manager = "bun"
pipx.uvx = true
aqua.baked_registry = false
