[tasks.dstop]
run = """
systemctl --user stop dv
systemctl --user stop openchamber
systemctl --user stop vscode
"""

[tasks.dstart]
run = """
systemctl --user start dv
systemctl --user start openchamber
systemctl --user start vscode
"""

[tasks.denable]
run = """
systemctl --user enable dv
systemctl --user enable openchamber
systemctl --user enable vscode
"""

[tasks.ddisable]
run = """
systemctl --user disable dv
systemctl --user disable openchamber
systemctl --user disable vscode
"""
